-- No-op: the "kautionsbuchungen" table (including its foreign keys to import_batches and
-- mietvertraege, and its index on mietvertragId) already exists in this database from an
-- earlier, since-reverted schema — its migration file was removed when that revert reset the
-- migration history, but the table itself was never dropped. Reintroducing the KautionBuchung
-- model here just picks that existing table back up; there is nothing left to create.
